name: teatimeapps
favicon: null
layout_spectrum: 0.94178
typography_spectrum: 0.5624017883092165
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6164700749795884
  lightness: 0.875
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
